### ISSUE TITLE
README is inconsistent

### ISSUE THREAD

**Issue by togakangaroo** [benschenker/console-hangman-implementaton#1]
the first thing I've been teaching them to do is to modify the README to write out a few sentences on what they're aiming for. The README still says it's a console.log game.

The first step (and it should be an explicit step) should be to get them to modify the README to what we're trying to do.

Last week, even after I explained what we were doing, most of the kids still were too timid (or didn't understand it enough to) write it down. You might want to explain it in a couple off different ways at the start.

Probably with some on-the-board wireframes.

**Comment by togakangaroo** [comment]
btw, understanding of what a wireframe is, is one of the things that john tested them for at the begining of the class

**Comment by benschenker** [comment]
Good catch, Fixed readme.

Also yes this is just kind of my first run through, I'll be setting up a new repo starting with a shell and making commits for each point of progress as we have done previously
