### ISSUE TITLE
Make button be type=button

### ISSUE THREAD

**Issue by togakangaroo** [benschenker/console-hangman-implementaton#4]
That way you don't have to get into `preventDefault` and try to explain that.

Also just use `<button id='play' type='button'>Start</button>`

Using input elements for that is old skool

**Comment by benschenker** [comment]
I had originally done this so that I could just press enter to submit the form....

**Comment by benschenker** [comment]
Yeah I think you are right about this...they don't need to press enter!

**Comment by benschenker** [comment]
fixed
